spring:
  application:
    name: webview
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    contentType: text/html
    cache: false
server:
  port: 9000
service:
  author: http://localhost:9001
  search: http://localhost:9002
