spring:
  application:
    name: author
  datasource:
  #数据库配置
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
#mybatis配置
mybatis:
  type-aliases-package: com.nmm.author.model
  mapper-locations: classpath:mapper/*.xml
server:
  port: 9001